title: Florent Grenier
description: >
  AI Engineer

  Python · C# · NLP · RAG · Computer Vision

  Toulouse (Blagnac)

  Développeur logiciel & IA chez VAL Software.
logo: /assets/img/profile.jpg
show_downloads: false
theme: jekyll-theme-merlot
